ctext = ''
ctext += '<TR>'
ctext += '	<TD align="left">'
ctext += '		<A HREF="http://citg.uthsc.edu/" target="_blank">'
ctext += '		<IMG SRC="/images/upload/CITGLogo.png" alt="CITG" border="0"></A>'
ctext += '	</TD>'
ctext += '	<TD align="left" id="smallsize" style="font-size:11px;font-family:verdana;color:black">'
ctext += 'WWW service initiated January, 1994 as <A HREF="http://www.ncbi.nlm.nih.gov/pubmed?term=8043953">The Portable Dictionary of the Mouse Genome</A> and June 15, 2001 as WebQTL.'
ctext += ''
ctext += 'This site is currently operated by'
ctext += '		<A class="smallsize" HREF="mailto:rwilliams@uthsc.edu">Rob Williams</A>,'
ctext += '		<A class="smallsize" HREF="mailto:lyan6@uthsc.edu">Lei Yan</A>,'
ctext += '		<A class="smallsize" HREF="mailto:zachary.a.sloan@gmail.com">Zachary Sloan</A>,'
ctext += '		<A class="smallsize" HREF="mailto:acenteno@uthsc.edu" target="_blank">Arthur Centeno</A>. Design and code by Xiaodong Zhou, Christian Fernandez, Ning Liu, Rudi Alberts, Elissa Chesler, Jintao Wang, Kenneth Manly, Robert W. Williams, and <A class="smallsize" HREF="/credit.html">colleagues</A>.'
ctext += ''
ctext += ''
ctext += '	</TD>'
ctext += '	<TD align="right">'
ctext += '		<A HREF="http://www.python.org/" target="_blank">'
ctext += '		<IMG src="/images/upload/PythonLogo.png" alt="Python Powered" border="0"></A>'
ctext += '	</TD>'
ctext += '	<TD align="right">'
ctext += '		<A HREF="http://www.neuinfo.org"  target="_blank">'
ctext += '		<img src="/images/upload/Nif.png" alt="Registered with Nif" border="0"></A>'
ctext += '	</TD>'
ctext += '</TR>'
ctext += '<TR>'
ctext += ''
ctext += '<!--  GENENETWORK SUPPORTED BY  -->'
ctext += ''
ctext += '	<TD colspan=4  style="font-size:12px;font-family:verdana;color:black">'
ctext += '		GeneNetwork support from:'
ctext += '		<UL>'
ctext += '		<LI><a class="smallsize" target="_blank" href="http://citg.uthsc.edu">The UT Center for Integrative and Translational Genomics</A>'
ctext += '		<LI><a class="smallsize" target="_blank" href="http://www.iniastress.org">NIAAA</A> Integrative Neuroscience Initiative on Alcoholism (U01AA13499, U24AA13513, U01AA014425)'
ctext += '		<LI><a class="smallsize" target="_blank" href="http://www.drugabuse.gov/about/organization/Genetics/geneexpression/index.html">NIDA</A>, <a class="smallsize" target="_blank" href="http://www.nimh.nih.gov/">NIMH</A>, and <a class="smallsize" target="_blank" href="http://www.niaaa.nih.gov/">NIAAA</A> (P20-DA 21131)'
ctext += '		<LI>NCI <a class="smallsize" target="_blank" href="http://emice.nci.nih.gov/">MMHCC</A> (U01CA105417), <a class="smallsize" target="_blank" href="http://www.ncrr.nih.gov/">NCRR</A> <a class="smallsize" target="_blank" href="http://www.nbirn.net/TestBeds/Mouse/index.htm">BIRN</A>,  (U24 RR021760)'
ctext += '		</UL>'
ctext += '	</TD>'
ctext += '</TR>'
ctext += '<TR>'
ctext += '	<TD colspan=4 id="smallsize" align="left">'
ctext += '		&nbsp;&nbsp;&nbsp;&nbsp;<!-- %s -->'
ctext += '	</TD>'
ctext += '</TR>'
document.write(ctext)