ctext = ''
ctext += '<TD width=30 rowSpan=5>&nbsp;</TD>'
ctext += '<TD bgColor=#ffffff NOWRAP="yes" width="100%" class="solidBorder">'
ctext += '	<Table width= "100%" cellSpacing=0 cellPadding=0>'
ctext += '		<TR>'
ctext += '			<TD width= "100%" id="smallsize">'
ctext += '				<a href="/">'
ctext += '				<IMG src="/images/upload/GeneNet_Banner2009c.png" border="0">'
ctext += '				</a>'
ctext += '			</TD>'
ctext += '			<TD valign="bottom">'
ctext += '				<A HREF="http://www.touchgraph.com/TGGoogleBrowser.php?start=genenetwork.org&signed=false" target="_blank">'
ctext += '					<IMG SRC="/images/upload/NetworkLogo.png" width="101" height="73" border="0">'
ctext += '				</a>'
ctext += '			</td>'
ctext += '			<TD valign="bottom">'
ctext += '				<IMG src="/images/webqtllogo2.gif" alt="WebQTL" border="0">'
ctext += '			</TD>'
ctext += '		</TR>'
ctext += '	</Table>'
ctext += '</TD>'
ctext += '<TD width="30" rowSpan=5>&nbsp;</TD>'
ctext += '</TR>'
ctext += '<TR>'
ctext += '<!--Home Help Search News Papers Policies Accounts Links-->'
ctext += '<TD bgColor=#ddddff NOWRAP="yes" class="solidBorder">'
ctext += '<table width="100%" cellSpacing=0 cellPadding=0 border=0>'
ctext += '<tr>'
ctext += '<td aligh=left NOWRAP="yes">'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp1" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp1\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp1\'])" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>Home</Strong></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp2" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp2\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp2\'])" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>Search</Strong></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp3" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp3\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp3\'])" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>Help</Strong></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp4" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp4\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp4\'])" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<A Href="/whats_new.html"  style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>News</Strong></A></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp5" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp5\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp5\'])" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<A Href="/reference.html"  style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>References</Strong></A></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp6" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp6\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp6\'])" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>Policies</Strong></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '<Span Id= "menu_grp8" onmouseover="A_MENUS[0].onmouseover(grpObj[\'menu_grp8\'])"  onmouseout="A_MENUS[0].onmouseout(grpObj[\'menu_grp8\'])"  style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<A Href="/links.html" style="font-size:12px;font-family:verdana;color:#0000ae">'
ctext += '<Strong>Links</Strong></A></Span>'
ctext += '&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;'
ctext += '</td>'
ctext += '<td align="right" NOWRAP="yes">'
ctext += '<!-- %s -->&nbsp;&nbsp;&nbsp;'
ctext += '</td>'
ctext += '</tr>'
ctext += '</table>'
ctext += '</TD>'
document.write(ctext)